apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{.Values.nodePort}}
  selector:
    app: jenkins
    type: NodePort
status:
  loadBalancer: {}