apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: pipeline
  labels:
    k8s-app: java-app
    project: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: java-app
  template:
    metadata:
      name: java-app
      labels:
        k8s-app: java-app
    spec:
      containers:
        - name: java-app
          image: andreichenko/java-app:v0.1.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          imagePullPolicy: IfNotPresent