---

aws_system_user: root
aws_profile: default
aws_access_key: "AKIA43NT7SJWXN4JIWVF"
aws_secret_key: "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"
aws_region: us-east-1
aws_format: json

kubectl_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
kubectl_version: "1.23.2"
kubectl_os: "linux"
kubectl_arch: "amd64"
kubectl_bin_directory: "/usr/local/bin"
kubectl_binary_mode: "0755"
kubectl_owner: "root"
kubectl_group: "root"