---

- hosts: "{{ hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root

  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python-pip
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=stable -y"

    - name: Add ansible repository
      shell: "amazon-linux-extras enable ansible2"

    - name: Install Ansible
      shell: "yum install -y ansible git"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
      vars:
        packages:
          - boto
          - boto3
          - docker-compose

    - name: Add user ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Add user jenkins to docker group
      user:
        name: dockeradmin
        groups: docker
        password: dockeradmin
        append: yes

    - name: Add user ansadmin to docker and root groups
      user:
        name: ansadmin
        password: ansadmin
        groups: docker
        append: yes



    - name: Download the awscli bundle.
      get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/tmp/awscli-bundle.zip
      register: aws_cli_download_bundle

    - name: Unarchive the installer.
      unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no creates=/tmp/awscli-bundle
      when: aws_cli_download_bundle.changed
      register: aws_cli_unarchive_installer

    - name: Install awscli package.
      shell: python /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/bin/aws
      args:
        creates: /usr/bin/aws
      when: aws_cli_unarchive_installer.changed

    - name: Configure AWS.
      shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
      with_dict:
        aws_access_key_id: "{{ aws_access_key }}"
        aws_secret_access_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        format: "{{ aws_format }}"
      become_user: "{{ aws_system_user }}"
      changed_when: false
      vars:
        aws_system_user: root
        aws_profile: default
        aws_access_key: "AKIAQU2NDSEN2WGJWM5Z"
        aws_secret_key: "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"
        aws_region: us-east-1
        aws_format: json

    - name: Download kubectl binary
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/{{ kubectl_os }}/{{ kubectl_arch }}/kubectl"
        dest: "{{ kubectl_tmp_directory }}"
      tags:
        - kubectl
      vars:
        kubectl_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
        kubectl_version: "1.23.2"
        kubectl_os: "linux"
        kubectl_arch: "amd64"

    - name: Copy kubectl binary to destination directory
      copy:
        src: "{{ kubectl_tmp_directory }}/{{ item }}"
        dest: "{{ kubectl_bin_directory }}/{{ item }}"
        mode: "{{ kubectl_binary_mode }}"
        owner: "{{ kubectl_owner }}"
        group: "{{ kubectl_group }}"
        remote_src: true
      with_items:
        - kubectl
      vars:
        kubectl_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
        kubectl_bin_directory: "/usr/local/bin"
        kubectl_binary_mode: "0755"
        kubectl_owner: "root"
        kubectl_group: "root"
