---

- hosts: "{{ hosts }}"
  become: yes
  remote_user: ubuntu
  become_user: root

  tasks:

    - name: 'Update the System Packages'
      apt:
        upgrade: 'yes'
        update_cache: yes

    - name: 'Create a Tomcat User'
      user:
        name: tomcat

    - name: 'Create a Tomcat Group'
      group:
        name: tomcat

    - name: 'Install JAVA'
      apt:
        name: default-jdk
        state: present

    - name: 'Create a Tomcat Directory'
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 0755
        recurse: yes

    - name: 'download & unarchive tomcat10'
      unarchive:
        src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: 'Change ownership of tomcat directory'
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: 'Copy Tomcat service from local to remote'
      copy:
        src: /etc/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: 'Start and Enable Tomcat 10 on sever'
      systemd:
        name: tomcat
        state: started
        enabled: yes
        daemon_reload: true
