name: 'CI/CD Project Validation'

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build-java:
    name: 'Build & Test Java App'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Run JUnit Tests
      run: mvn test

  validate-terraform:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      run: |
        cd terraform
        terraform init -backend=false

    - name: Terraform Validate
      env:
        TF_VAR_public_key_path: fake_key.pub
      run: |
        cd terraform
        touch fake_key.pub
        terraform validate
